# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Peeling Away the Layers of the Network Stack
email: ufuk@paralaus.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://peelingawaythelayers.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paracycle
github_username:  paracycle
livereload: true

# Build settings
# theme: minima
markdown: Pandoc
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-pandoc
css_dir: assets/css/

pandoc:
  extensions:
    - from: markdown+emoji+smart+fenced_code_blocks
    - no-highlight
    - mathjax

collections:
  pages:
    path: _pages
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - .now

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
